AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  StudentScoresTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StudentScoresV02
      AttributeDefinitions:
        - AttributeName: studentTeacherHash
          AttributeType: S
      KeySchema:
        - AttributeName: studentTeacherHash
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StudentPreferencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: StudentPreferences
      AttributeDefinitions:
        - AttributeName: studentName
          AttributeType: S
      KeySchema:
        - AttributeName: studentName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  PostStudentResults:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Handler: main.post_student_results
      Runtime: python3.13
      Policies:
        - DynamoDBCrudPolicy:
            TableName: StudentScoresV02
      Environment:
        Variables:
          TABLE_NAME: StudentScoresV02
      Events:
        Api:
          Type: Api
          Properties:
            Path: /results
            Method: POST


  GetStudentScores:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.get_scores
      Runtime: python3.13
      Policies:
        - DynamoDBReadPolicy:
            TableName: StudentScoresV02
      Environment:
        Variables:
          TABLE_NAME: StudentScoresV02
      Events:
        Api:
          Type: Api
          Properties:
            Path: /student_scores
            Method: GET

  SetStudentPreferences:
    Type: AWS::Serverless::Function
    Properties:
      Handler: set_preferences.lambda_handler
      Runtime: python3.13
      Policies:
        - DynamoDBCrudPolicy:
            TableName: StudentPreferences
      Environment:
        Variables:
          TABLE_NAME: StudentPreferences
      Events:
        Api:
          Type: Api
          Properties:
            Path: /student/{studentName}/preferences
            Method: POST

  GetStudentPreferences:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_preferences.lambda_handler
      Runtime: python3.13
      Policies:
        - DynamoDBReadPolicy:
            TableName: StudentPreferences
      Environment:
        Variables:
          TABLE_NAME: StudentPreferences
      Events:
        Api:
          Type: Api
          Properties:
            Path: /student/{studentName}
            Method: GET

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
